### ISSUE TITLE
Properly expose copy-in-the-cloud functionality

### ISSUE THREAD

**Issue by ezk84** [GoogleCloudPlatform/appengine-gcs-client#5]
Currently the GCS API's [copy-in-the-cloud method](https://developers.google.com/storage/docs/json_api/v1/objects/copy) is exposed as an "internal only" function `cloudstorage.storage_api._copy2`. This is a useful function for general users and it would be nicer to be able to access this functionality with this library officially, rather than having to use the Google API Client to access the lower level JSON API just for this.

**Comment by tkaitchuck** [comment]
I am fine with exposing this. If you want to create a pull request that adds a copy2 method that delegates to it, that would work.

**Comment by ezk84** [comment]
Is this suggestion still valid, or was it deleted?

**Comment by tkaitchuck** [comment]
I removed it because @BrandonY had more informed opinions about it. I expected he would chime in.
Brandon? Thoughts?

**Comment by BrandonY** [comment]
Hey. After chatting with a couple of people, I see no reason we couldn't expose the copy method.
