### ISSUE TITLE
Differences between appengine-gcs-client and google-cloud-storage

### ISSUE THREAD

**Issue by Burtan** [GoogleCloudPlatform/appengine-gcs-client#58]
Hi,
when should I use this library and when should I use [google-cloud-storage](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-storage)? They seem to do the same.

**Comment by BrandonY** [comment]
You should prefer google-cloud-java. This library has a couple of App Engine-specific advantages over that library, mainly its support for providing a local GCS when programming against a local development server, but in general the other library is newer, more feature rich, and better maintained.

**Comment by elharo** [comment]
Can someone please close this bug?
