### ISSUE TITLE
Avoid using dependency version ranges

### ISSUE THREAD

**Issue by gabor-farkas** [GoogleCloudPlatform/appengine-gcs-client#71]
Due to the issue with google-http-java-client https://github.com/google/google-http-java-client/issues/438 our production build just started to fail today morning. Such an issue shouldn't threaten anyone's build, but such errors can escalate quickly is dependency ranges are used in released dependencies.
The version `<version>[1.19,2.0)</version>` used in the pom should be replaced to a fix, release version to ensure build stability.

**Comment by elharo** [comment]
Not the first time this has happened either:

https://stackoverflow.com/questions/38537416/maven-build-error-in-jenkins-semi-time-sensitive/38537760

**Comment by ludoch** [comment]
Version 0.8 is now pushed. Please verify.
