### ISSUE TITLE
Pin specific versions in pom.xml

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/appengine-gcs-client#72]
That is no version ranges. As I type this, customer builds and deploys are broken by a google-http-client push. This wouldn't have happened with specific pinned versions. See b/112072623

**Comment by garrettjonesgoogle** [comment]
Specifically the ranges like this are a problem: https://github.com/GoogleCloudPlatform/appengine-gcs-client/blob/master/java/pom.xml#L124

**Comment by gebba** [comment]
Experiencing the same problem, but I think this was already reported in #71

**Comment by elharo** [comment]
Yep, #71 is the same issue. Closing this as a dup.
